version: '3.3'

services:
    mainapi:
        build:
            context: ./backend
        ports:
          - 4000:4000
        restart: always
        tty: true
        #depends_on:
        # - prisma
        networks: 
          - internal

networks:
  internal:
    # prisma:
    #     image: prismagraphql/prisma:1.34
    #     restart: always
    #     ports:
    #     - "4466:4466"
    #     networks: 
    #         - web
    #         - internal
    #     environment:
    #        PRISMA_CONFIG: |
    #          port: 4466
    #          databases:
    #            default:
    #              connector: postgres
    #              host: ${DB_HOST}
    #              port: 5432
    #              user: ${MAIN_DB_USER}
    #              password: ${MAIN_DB_PASSWORD}
    #              database: ${MAIN_DB_NAME}
    #             #  schema: public
    #              migrations: true
